#%RAML 1.0
title: QA Cinemas
version: 1.0
baseUri: http://apps.qacinemas.com/api/
/getFilms:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              [{
                "film": "Wonder Woman",
                "genre": "Action"
              },
              {
                "film": "Despicable Me 3",
                "genre": "Family"
              }]
  /byGenre:
    get:
      queryParameters: 
        genre:
          required: true
          enum: [action, drama, family]
      responses:
        200:
          body:
            application/json:
              example: |
                [{
                  "film": "Wonder Woman",
                  "genre": "Action"
                },
                {
                  "film": "Despicable Me 3",
                  "genre": "Family"
                }]
    